### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by SingaravelC** [federicopepedev/wp-ai-assistant#1]
Plugin could not be activated because it triggered a fatal error.  please solve this issues.

**Comment by federicopepedev** [comment]
I am sorry to hear about the issues you are having with this plugin.

Could you please provide this information? I need additional details to reproduce your issue to troubleshoot it.

- PHP Version
- WordPress Version

Could you enable the WordPress Debug Mode or check your site administrator email and then try to activate the plugin? It will give you a detailed error message.
